<a href="https://colab.research.google.com/github/akuma527/IProjects/blob/master/I%26D_Whale/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [2]:
%cd /content/drive/My Drive/Colab Notebooks/I&D_Whale/data/

/content/drive/My Drive/Colab Notebooks/I&D_Whale/data

In [0]:
import os
import pandas as pd
import cv2

In [7]:
os.listdir()

['test',
 'train',
 'pickled_obj',
 'train.csv',
 'test.csv',
 '.ipynb_checkpoints',
 'same_images.csv']

In [0]:
train = pd.read_csv('train.csv')
img_rep = pd.read_csv('same_images.csv')

In [9]:
train.head()

                     Image  Id                                fil_path
0  PM-WWA-20050416-037.jpg  -1  train/train/-1/PM-WWA-20050416-037.jpg
1  PM-WWA-20050513-229.jpg  -1  train/train/-1/PM-WWA-20050513-229.jpg
2  PM-WWA-20050513-243.jpg  -1  train/train/-1/PM-WWA-20050513-243.jpg
3  PM-WWA-20050520-134.jpg  -1  train/train/-1/PM-WWA-20050520-134.jpg
4  PM-WWA-20050612-047.jpg  -1  train/train/-1/PM-WWA-20050612-047.jpg

In [10]:
img_rep.head()

                          0                         1    2  ...   34   35   36
0           IMG_2270-16.jpg                       NaN  NaN  ...  NaN  NaN  NaN
1  PM-WWA-20050413-003a.jpg                       NaN  NaN  ...  NaN  NaN  NaN
2  PM-WWA-20050413-003b.jpg   PM-WWA-20050413-029.jpg  NaN  ...  NaN  NaN  NaN
3   PM-WWA-20050413-029.jpg  PM-WWA-20050413-003b.jpg  NaN  ...  NaN  NaN  NaN
4   PM-WWA-20050413-006.jpg   PM-WWA-20050413-007.jpg  NaN  ...  NaN  NaN  NaN

[5 rows x 37 columns]

In [0]:
df = pd.merge(train, img_rep, left_on='Image', right_on='0', how='left')

In [18]:
df['Id'].unique()

array(['-1', '0161', '0836', ..., 'cf_of_fingers', 'cf_of_whitehead',
       'nike'], dtype=object)

In [22]:
df[df['Id']=='cf_of_fingers'].describe()

                          Image             Id  ...   35   36
count                         2              2  ...    0    0
unique                        2              1  ...    0    0
top     PM-WWA-20120801-038.jpg  cf_of_fingers  ...  NaN  NaN
freq                          1              2  ...  NaN  NaN

[4 rows x 40 columns]